---
title: "Medicaid Expansion and Opioid Misuse Disorder in the US"
subtitle: "Final Project"
format: pdf
bibliography: references.bib
csl: chicago-author-date.csl
author:
  - name: Naomi Buell
  - name: Richie Rivera
  - name: Alexander Simon
  - name: Nana Frimpong
  - name: Said Naqwe
date: April 26, 2026
documentclass: article
classoption: 11pt
geometry:
  - margin=1in
header-includes:
  - \usepackage{fancyhdr}
  - \usepackage{setspace}
  - \onehalfspacing
  - \pagestyle{fancy}
  - \lhead{DATA 621}
  - \rhead{Naomi Buell, Richie Rivera, Alexander Simon, Nana Frimpong, Said Naqwe}
  - \setcounter{secnumdepth}{7}
---

```{r}
#| label: load-packages
#| include: false
# Load necessary libraries
library(tidyverse)
library(skimr)
library(corrplot)
library(GGally)
library(janitor)
library(pROC)
library(fastDummies)
library(tidytable)
```

# Abstract (Naomi)
*Use 250 words or less to summarize your problem, methodology, and major outcomes.*

# Key words (Naomi)
*Select a few key words (up to five) related to your work.*

# Introduction (Naomi)
*Describe the background and motivation of your problem.*

# Literature review (Alex)
*Discuss how other researchers have addressed similar problems, what their achievements are, and what the advantage and drawbacks of each reviewed approach are. Explain how your investigation is similar or different to the state-of-the- art. Please cite the relevant papers where appropriate.*

Example citation [@Volkow2019].

# Methodology
*Discuss the key aspects of your problem, data set and regression model(s). Given that you are working on real-world data, explain at a high-level your exploratory data analysis, how you prepared the data for regression modeling, your process for building regression models, and your model selection.*

## Exploratory Data Analysis (Naomi)

## Data Preparation methods (Nana)

## Build models methods ()

## Select models methods ()

# Experimentation and Results
*Describe the specifics of what you did (data exploration, data preparation, model building, model selection, model evaluation, etc.), and what you found out (statistical analyses, interpretation and discussion of the results, etc.).*

## Exploratory Data Analysis (Naomi)

## Results of Data Preparation (Nana)

## Results of Building models ()

## Results of model selection ()

# Discussion and Conclusions ()
*Conclude your findings, limitations, and suggest areas for future work.*

# References
